spring:
  application:
    name: gateway-service

server:
  port: 8302


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://localhost:8302/eureka

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    get-employee-service:
      path: /get-employee-service/**
      sensitiveHeaders:
      url: http://localhost:8301
    add-employee-service:
      path: /add-employee-service/**
      sensitiveHeaders:
      url: http://localhost:8303